# Generated by Django 2.0.13 on 2019-04-01 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20190331_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenModel',
            fields=[
                ('token', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oauth.AppModel')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='refreshtokenmodel',
            unique_together={('app', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='tokenmodel',
            unique_together={('app', 'student')},
        ),
    ]
