# Generated by Django 2.0.13 on 2019-04-06 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_auto_20190401_2336'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='refreshtokenmodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tokenmodel',
            unique_together=set(),
        ),
    ]
