# Generated by Django 2.0.13 on 2019-04-24 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_auto_20190406_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstokenmodel',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.AppModel'),
        ),
        migrations.AlterField(
            model_name='accesstokenmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appservicerelmodel',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.AppModel'),
        ),
        migrations.AlterField(
            model_name='appservicerelmodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.ServiceModel'),
        ),
        migrations.AlterField(
            model_name='refreshtokenmodel',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.AppModel'),
        ),
        migrations.AlterField(
            model_name='refreshtokenmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tokenmodel',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.AppModel'),
        ),
        migrations.AlterField(
            model_name='tokenmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
